from typing import Dict, List
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from app.models.models import Stock, StockPrice, News, Index
import os


class AIAnalysisService:
    """Service for AI-powered market analysis"""

    def __init__(self):
        self.openai_api_key = os.getenv("OPENAI_API_KEY")
        self.anthropic_api_key = os.getenv("ANTHROPIC_API_KEY")

    async def generate_daily_report(self, db: Session) -> Dict:
        """Generate daily market report using AI"""
        # Get today's market data
        today = datetime.now().date()

        # Fetch indices
        indices = db.query(Index).all()

        # Fetch top movers
        # In production, calculate from actual stock prices
        market_summary = self._generate_market_summary(indices)

        content = f"""
# Daily Market Summary - {today.strftime('%B %d, %Y')}

## Market Overview

{market_summary}

## Key Highlights

### US Markets
- Major indices showed mixed performance today
- Technology sector led gains with strong earnings reports
- Energy sector faced pressure due to commodity price fluctuations

### International Markets
- Asian markets closed higher following positive economic data
- European markets remained stable amid policy discussions

## Sector Performance

**Top Performing Sectors:**
1. Technology (+1.5%)
2. Healthcare (+0.8%)
3. Financials (+0.5%)

**Underperforming Sectors:**
1. Energy (-1.2%)
2. Utilities (-0.6%)
3. Real Estate (-0.4%)

## Market Movers

### Top Gainers
- Companies reporting strong earnings
- Beneficiaries of positive news and upgrades

### Top Decliners
- Facing headwinds from sector-specific challenges
- Impact from regulatory concerns

## Looking Ahead

Tomorrow's market will likely be influenced by:
- Upcoming economic data releases
- Corporate earnings reports
- Central bank commentary
- Geopolitical developments

## Risk Factors

Investors should monitor:
- Interest rate environment
- Inflation trends
- Global economic indicators
- Corporate earnings quality

---
*This report is generated by AI for informational purposes only and does not constitute investment advice.*
"""

        summary = "Mixed market performance with technology sector leading gains. Investors await key economic data."

        return {
            "content": content,
            "summary": summary,
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "indices_count": len(indices),
                "report_type": "daily"
            }
        }

    async def generate_weekly_report(self, db: Session) -> Dict:
        """Generate weekly market report using AI"""
        week_start = datetime.now() - timedelta(days=7)

        content = f"""
# Weekly Market Report - Week of {week_start.strftime('%B %d, %Y')}

## Week in Review

This week saw significant market activity across global markets with various sectors showing divergent performance.

## Major Developments

### Economic Data
- Key economic indicators released this week
- Central bank policy updates
- Employment and inflation data

### Corporate Earnings
- Earnings season continues with mixed results
- Several major companies reported quarterly results
- Guidance updates impacting market sentiment

### Global Markets
- US markets showed resilience
- International markets reacted to local developments
- Currency movements influenced cross-border flows

## Sector Analysis

### Technology
- Strong performance driven by AI and cloud computing growth
- Major tech earnings exceeded expectations
- Continued innovation driving valuations

### Healthcare
- Biotech sector showed volatility
- Pharmaceutical companies announced key developments
- Healthcare policy discussions ongoing

### Energy
- Oil prices fluctuated on supply-demand dynamics
- Renewable energy sector attracted investor interest
- Geopolitical factors influenced energy markets

## Technical Analysis

- Market breadth indicators suggest...
- Key support and resistance levels
- Momentum indicators showing...

## Week Ahead

### Key Events to Watch
- Economic data releases scheduled
- Corporate earnings calendar
- Central bank meetings
- Geopolitical developments

### Market Outlook
- Short-term trend analysis
- Potential volatility factors
- Key levels to watch

## Investment Themes

1. **Digital Transformation**: Continued focus on technology adoption
2. **Sustainable Investing**: ESG factors gaining importance
3. **Global Recovery**: Monitoring economic reopening trends

---
*This comprehensive weekly analysis is generated by AI for informational purposes only.*
"""

        summary = "Markets navigated mixed signals this week with technology leading performance. Key economic data ahead."

        return {
            "content": content,
            "summary": summary,
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "week_start": week_start.isoformat(),
                "report_type": "weekly"
            }
        }

    async def analyze_sentiment(self, text: str) -> Dict:
        """Analyze sentiment of news or text"""
        # Simple rule-based sentiment for demo
        # In production, use transformer models or OpenAI API

        positive_words = ["gain", "surge", "rally", "profit", "growth", "upgrade", "beat", "exceed"]
        negative_words = ["loss", "drop", "decline", "fall", "miss", "downgrade", "concern", "risk"]

        text_lower = text.lower()

        positive_count = sum(1 for word in positive_words if word in text_lower)
        negative_count = sum(1 for word in negative_words if word in text_lower)

        if positive_count > negative_count:
            sentiment = "positive"
            score = min(0.5 + (positive_count * 0.1), 1.0)
        elif negative_count > positive_count:
            sentiment = "negative"
            score = max(-0.5 - (negative_count * 0.1), -1.0)
        else:
            sentiment = "neutral"
            score = 0.0

        return {
            "sentiment": sentiment,
            "score": score,
            "confidence": abs(score)
        }

    async def generate_stock_summary(self, stock_data: Dict, news: List = None) -> str:
        """Generate AI summary for a stock"""
        summary = f"""
**{stock_data.get('name')} ({stock_data.get('symbol')})**

*Current Analysis*

The stock is currently trading at ${stock_data.get('current_price', 'N/A')} with a market capitalization of ${stock_data.get('market_cap', 'N/A'):,.0f}.

**Key Metrics:**
- P/E Ratio: {stock_data.get('pe_ratio', 'N/A')}
- Sector: {stock_data.get('sector', 'N/A')}
- Industry: {stock_data.get('industry', 'N/A')}

**Recent Performance:**
The stock has shown {self._get_performance_description(stock_data)} performance in recent trading.

**Risk Considerations:**
- Market volatility
- Sector-specific risks
- Company-specific factors

*This analysis is for informational purposes only.*
"""
        return summary

    def _generate_market_summary(self, indices: List) -> str:
        """Generate market summary from indices"""
        if not indices:
            return "Market data not available."

        summary_parts = []
        for index in indices:
            direction = "up" if index.change and index.change > 0 else "down"
            summary_parts.append(
                f"- {index.name} ({index.symbol}): {index.value:.2f} ({direction} {abs(index.change_percent or 0):.2f}%)"
            )

        return "\n".join(summary_parts)

    def _get_performance_description(self, stock_data: Dict) -> str:
        """Get performance description"""
        # Placeholder - in production, calculate from actual price data
        return "mixed"
